import { Document, Page, StyleSheet, Text, View, pdf } from '@react-pdf/renderer';
import { buildLeaderboard, sortLeaderboard } from '@/lib/leaderboard';
import type { EventPlayerRow, EventRow, GameRow, PlayerRow } from '@/types/db';

const styles = StyleSheet.create({
  page: { padding: 28, fontSize: 10, fontFamily: 'Helvetica' },
  h1: { fontSize: 16, fontWeight: 700, marginBottom: 4 },
  sub: { fontSize: 9, color: '#666', marginBottom: 14 },
  table: { display: 'flex', flexDirection: 'column', borderWidth: 1, borderColor: '#ddd' },
  row: { flexDirection: 'row', borderBottomWidth: 1, borderBottomColor: '#ddd' },
  rowLast: { flexDirection: 'row' },
  headerRow: {
    flexDirection: 'row',
    backgroundColor: '#f4f4f5',
    borderBottomWidth: 1,
    borderBottomColor: '#ddd',
  },
  cell: { padding: 4, borderRightWidth: 1, borderRightColor: '#eee' },
  cellLast: { padding: 4 },
  colRank: { width: 28 },
  colPlayer: { flexGrow: 1 },
  colNum: { width: 50, textAlign: 'right' },
  colHdcp: { width: 40, textAlign: 'right' },
  bold: { fontWeight: 700 },
  footer: { marginTop: 16, fontSize: 8, color: '#888' },
});

interface PdfProps {
  event: EventRow;
  eventPlayers: Array<EventPlayerRow & { player: PlayerRow }>;
  games: GameRow[];
}

function StandingsDoc({ event, eventPlayers, games }: PdfProps) {
  const rows = sortLeaderboard(buildLeaderboard(eventPlayers, games, []), 'scratchSeries');

  return (
    <Document>
      <Page size="LETTER" style={styles.page}>
        <Text style={styles.h1}>{event.name}</Text>
        <Text style={styles.sub}>
          {event.type.toUpperCase()} · {event.start_date}
          {event.end_date ? ` → ${event.end_date}` : ''}
          {event.center_name ? ` · ${event.center_name}` : ''}
        </Text>

        <View style={styles.table}>
          <View style={styles.headerRow}>
            <Text style={[styles.cell, styles.colRank, styles.bold]}>#</Text>
            <Text style={[styles.cell, styles.colPlayer, styles.bold]}>Player</Text>
            <Text style={[styles.cell, styles.colHdcp, styles.bold]}>Hdcp</Text>
            <Text style={[styles.cell, styles.colNum, styles.bold]}>Games</Text>
            <Text style={[styles.cell, styles.colNum, styles.bold]}>Scratch</Text>
            <Text style={[styles.cell, styles.colNum, styles.bold]}>Handicap</Text>
            <Text style={[styles.cell, styles.colNum, styles.bold]}>High</Text>
            <Text style={[styles.cellLast, styles.colNum, styles.bold]}>Avg</Text>
          </View>
          {rows.map((r, i) => {
            const last = i === rows.length - 1;
            const rowStyle = last ? styles.rowLast : styles.row;
            return (
              <View key={r.eventPlayerId} style={rowStyle}>
                <Text style={[styles.cell, styles.colRank]}>{i + 1}</Text>
                <Text style={[styles.cell, styles.colPlayer]}>{r.playerName}</Text>
                <Text style={[styles.cell, styles.colHdcp]}>{r.handicap}</Text>
                <Text style={[styles.cell, styles.colNum]}>{r.gamesPlayed}</Text>
                <Text style={[styles.cell, styles.colNum]}>{r.scratchSeries}</Text>
                <Text style={[styles.cell, styles.colNum]}>{r.handicapSeries}</Text>
                <Text style={[styles.cell, styles.colNum]}>{r.highGame}</Text>
                <Text style={[styles.cellLast, styles.colNum]}>
                  {r.average !== null ? r.average.toFixed(1) : '-'}
                </Text>
              </View>
            );
          })}
        </View>

        <Text style={styles.footer}>
          Generated by BowlTrack · {new Date().toLocaleString()}
        </Text>
      </Page>
    </Document>
  );
}

export async function downloadStandingsPdf(
  event: EventRow,
  eventPlayers: Array<EventPlayerRow & { player: PlayerRow }>,
  games: GameRow[]
) {
  const blob = await pdf(
    <StandingsDoc event={event} eventPlayers={eventPlayers} games={games} />
  ).toBlob();
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = `${slugify(event.name)}-standings.pdf`;
  a.click();
  URL.revokeObjectURL(url);
}

function slugify(s: string) {
  return s
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^-+|-+$/g, '')
    .slice(0, 60) || 'standings';
}
